---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/agent

inputs:
- name: bosh-linux-stemcell-builder
- name: version

params: {}

run:
  path: bosh-linux-stemcell-builder/ci/tasks/assert-version-aligns.sh
