---
groups:
  - name: all
    jobs:
      - new-version
      - build-stemcell
      - publish-stemcells
      - build-cloudstack-xen-centos-7
      - build-cloudstack-xen-ubuntu-trusty
  - name: cloudstack
    jobs:
      - build-cloudstack-xen-ubuntu-trusty
      - build-cloudstack-xen-centos-7

jobs:

  - name: new-version
    plan:
    - get: published-stemcell
      trigger: true
    - get: bosh-src
    - task: make-version
      file: bosh-src/ci/pipelines/stemcells/tasks/make-stemcell-version.yml
    - put: version
      params: {file: out/semver}



  - name: build-stemcell
    serial: true
    plan:
      - get: bosh-src
      - get: ubuntu-trusty-os-image
      - get: centos-7-os-image
      - get: bosh-release
      - get: version
        passed: [new-version]
#        params:
#          bump: major
#      - put: version
#        params:
#          file: version/number

  - name: publish-stemcells
    serial: true
    plan:
      - get: version
        trigger: true
        passed:
          - build-stemcell
          - build-cloudstack-xen-ubuntu-trusty
          - build-cloudstack-xen-centos-7          
      - get: bosh-src
        passed:
          - build-stemcell
          - build-cloudstack-xen-ubuntu-trusty
          - build-cloudstack-xen-centos-7          
      - task: copy-artifacts
        file: bosh-src/ci/pipelines/stemcell/tasks/publish.yml
        params:
          AWS_ACCESS_KEY_ID: {{stemcell_aws_access_key}}
          AWS_SECRET_ACCESS_KEY: {{stemcell_aws_secret_key}}
          BUCKET_NAME: {{stemcell_bucket}}
          CANDIDATE_PREFIX: bosh-stemcell-candidate/
          PUBLISHED_PREFIX: bosh-stemcell/
          COPY_KEYS: |
            cloudstack/bosh-stemcell-%s-cloudstack-xen-ubuntu-trusty-go_agent.tgz.sha1
            cloudstack/bosh-stemcell-%s-cloudstack-xen-ubuntu-trusty-go_agent.tgz
            cloudstack/bosh-stemcell-%s-cloudstack-xen-centos-7-go_agent.tgz.sha1
            cloudstack/bosh-stemcell-%s-cloudstack-xen-centos-7-go_agent.tgz


  #
  # cloudstack
  #
  - name: build-cloudstack-xen-ubuntu-trusty
    plan:
      - aggregate:
          - get: version
            trigger: true
            passed: [build-stemcell]
          - get: bosh-src
            passed: [build-stemcell]
          - get: bosh-release
            passed: [build-stemcell]
          - get: os-image
            resource: ubuntu-trusty-os-image
            passed: [build-stemcell]
      - task: create-stemcell
        file: bosh-src/ci/pipelines/stemcell/tasks/build.yml
        privileged: true
        config:
          params:
            IAAS:       cloudstack
            HYPERVISOR: xen
            OS_NAME:    ubuntu
            OS_VERSION: trusty
      - aggregate:
        - put: cloudstack-xen-ubuntu-trusty
          params:
            file: stemcell/*-go_agent.tgz
        - put: cloudstack-xen-ubuntu-trusty-sha1
          params:
            file: stemcell/*-go_agent.tgz.sha1

  - name: build-cloudstack-xen-centos-7
    plan:
      - aggregate:
          - get: version
            trigger: true
            passed: [build-stemcell]
          - get: bosh-src
            passed: [build-stemcell]
          - get: bosh-release
            passed: [build-stemcell]
          - get: os-image
            resource: centos-7-os-image
            passed: [build-stemcell]
      - task: create-stemcell
        file: bosh-src/ci/pipelines/stemcell/tasks/build.yml
        privileged: true
        config:
          params:
            IAAS:       cloudstack
            HYPERVISOR: xen
            OS_NAME:    centos
            OS_VERSION: 7
      - aggregate:
        - put: cloudstack-xen-centos-7
          params:
            file: stemcell/*-go_agent.tgz
        - put: cloudstack-xen-centos-7-sha1
          params:
            file: stemcell/*-go_agent.tgz.sha1

resources:
  - name: bosh-src
    type: git
    source:
      uri: {{bosh-repo}}
      branch: {{branch}}

  - name: version
    type: semver
    source:
      driver: s3
      key: bosh-stemcell/version
      bucket: {{stemcell_bucket}}
      access_key_id: {{stemcell_aws_access_key}}
      secret_access_key: {{stemcell_aws_secret_key}}
      
      
  - name: published-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
      tarball: false

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  #
  # os-images
  #
  - name: ubuntu-trusty-os-image
    type: s3
    source:
      bucket: {{osimage_bucket}}
      regexp: ubuntu-trusty/ubuntu-trusty-(.+).tgz

  - name: centos-7-os-image
    type: s3
    source:
      bucket: {{osimage_bucket}}
      regexp: centos-7/centos-7-(.+).tgz

  #
  # cloudstack
  #

  - name: cloudstack-xen-ubuntu-trusty
    type: s3
    source:
      bucket: {{stemcell_bucket}}
      regexp: bosh-stemcell-candidate/cloudstack/bosh-stemcell-(.+)-cloudstack-xen-ubuntu-trusty-go_agent.tgz
      access_key_id: {{stemcell_aws_access_key}}
      secret_access_key: {{stemcell_aws_secret_key}}

  - name: cloudstack-xen-centos-7
    type: s3
    source:
      bucket: {{stemcell_bucket}}
      regexp: bosh-stemcell-candidate/cloudstack/bosh-stemcell-(.+)-cloudstack-xen-centos-7-go_agent.tgz
      access_key_id: {{stemcell_aws_access_key}}
      secret_access_key: {{stemcell_aws_secret_key}}


  - name: cloudstack-xen-ubuntu-trusty-sha1
    type: s3
    source:
      bucket: {{stemcell_bucket}}
      regexp: bosh-stemcell-candidate/cloudstack/bosh-stemcell-(.+)-cloudstack-xen-ubuntu-trusty-go_agent.tgz.sha1
      access_key_id: {{stemcell_aws_access_key}}
      secret_access_key: {{stemcell_aws_secret_key}}


  - name: cloudstack-xen-centos-7-sha1
    type: s3
    source:
      bucket: {{stemcell_bucket}}
      regexp: bosh-stemcell-candidate/cloudstack/bosh-stemcell-(.+)-cloudstack-xen-centos-7-go_agent.tgz.sha1
      access_key_id: {{stemcell_aws_access_key}}
      secret_access_key: {{stemcell_aws_secret_key}}


