---
jobs:
- name: new-version
  plan:
  - get: published-stemcell
    trigger: true
  - get: bosh-src
  - task: make-version
    file: bosh-src/ci/pipelines/stemcells/tasks/make-stemcell-version.yml
  - put: stemcell-version
    params: {file: make-version/semver}

- name: build-ubuntu-trusty
  plan:
  - get: bosh-src
    passed: [new-version]
  - get: stemcell-version
    passed: [new-version]
    trigger: true
    
  - task: create-stemcell
    file: bosh-src/ci/pipelines/stemcell/tasks/build.yml
    privileged: true
    params:
      IAAS:       cloudstack
      HYPERVISOR: xen
      OS_NAME:    ubuntu
      OS_VERSION: trusty
    
  - put: candidate-stemcell-ubuntu-trusty
    params: {from: build/out/.+\.tgz}

- name: build-centos-7
  plan:
  - get: bosh-src
    passed: [new-version]
  - get: stemcell-version
    passed: [new-version]
    trigger: true

  - task: create-stemcell
    file: bosh-src/ci/pipelines/stemcell/tasks/build.yml
    privileged: true
    params:
      IAAS:       cloudstack
      HYPERVISOR: xen
      OS_NAME:    centos
      OS_VERSION: "7"
  - put: candidate-stemcell-centos-7
    params: {from: build/out/.+\.tgz}

- name: promote
  plan:
  - get: stemcell-version
    passed: [build-ubuntu-trusty, build-centos-7]
    trigger: true
  - get: candidate-stemcell-ubuntu-trusty
    passed: [build-ubuntu-trusty]
  - get: candidate-stemcell-centos-7
    passed: [build-centos-7]
  - put: final-stemcell-ubuntu-trusty
    params: {from: candidate-stemcell-ubuntu-trusty/.+\.tgz}
  - put: final-stemcell-centos-7
    params: {from: candidate-stemcell-centos-7/.+\.tgz}

resources:
- name: bosh-src
  type: git
  source:
    #uri: https://github.com/cloudfoundry/bosh.git  <-- should externalize in concourse props
    uri: {{bosh-repo}}
    branch: {{branch}}

- name: published-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    tarball: false

- name: stemcell-version
  type: semver
  source:
    key: stemcell-version
    bucket: {{s3_candidate_stemcell_bucket_name}}
    access_key_id: {{aws_builder_access_key}}
    secret_access_key: {{aws_builder_secret_access_key}}

- name: candidate-stemcell-ubuntu-trusty
  type: s3
  source:
    regexp: bosh-stemcell-([0-9]+)-cloustack-xen-ubuntu-trusty-go_agent.tgz
    bucket: {{s3_candidate_stemcell_bucket_name}}
    access_key_id: {{aws_builder_access_key}}
    secret_access_key: {{aws_builder_secret_access_key}}

- name: candidate-stemcell-centos-7
  type: s3
  source:
    regexp: bosh-stemcell-([0-9]+)-cloudstack-xen-centos-7-go_agent.tgz
    bucket: {{s3_candidate_stemcell_bucket_name}}
    access_key_id: {{aws_builder_access_key}}
    secret_access_key: {{aws_builder_secret_access_key}}

- name: final-stemcell-ubuntu-trusty
  type: s3
  source:
    regexp: bosh-stemcell-([0-9]+)-cloudstack-xen-ubuntu-trusty-go_agent.tgz
    bucket: {{s3_final_stemcell_bucket_name}}
    access_key_id: {{aws_builder_access_key}}
    secret_access_key: {{aws_builder_secret_access_key}}

- name: final-stemcell-centos-7
  type: s3
  source:
    regexp: bosh-stemcell-([0-9]+)-cloudstack-xen-centos-7-go_agent.tgz
    bucket: {{s3_final_stemcell_bucket_name}}
    access_key_id: {{aws_builder_access_key}}
    secret_access_key: {{aws_builder_secret_access_key}}
